version: "3.9"
services:
  postgres:
    container_name: Postgres
    build: Dockerfile-Postgres
    environment:
      - POSTGRES_PASSWORD=mdp
      - POSTGRES_USER=admin
    ports:
      - 5432:5432
    volumes: 
      - "./pgsql-scripts:/docker-entrypoint-initdb.d"
      - "postgres-volume:/var/lib/postgresql/data"
    networks:
      net: {}

  redis:
    container_name: Redis
    build: Dockerfile-Redis
    ports:
      - 6379:6379
    volumes: 
      - ./volumes/volume-redis:/data
    networks:
      net: {}

  
  apache-flask:
    container_name: Apache-Flask
    build: Dockerfile-Apache
    ports:
      - 8888:80
    networks:
      net: {}


  admirer:
    image: adminer
    ports:
      - 8020:8080
    networks:
      net: {}

networks:
  net: {}

volumes:
  postgres-volume: