version: "3.9"
services:
  postgres:
    build:
      context: Dockerfile-Postgres
      dockerfile: dockerfile-postgres
    environment:
      - POSTGRES_PASSWORD=mdp
      - POSTGRES_USER=admin
    ports:
      - 5432:5432
    volumes: 
      - "./pgsql-scripts:/docker-entrypoint-initdb.d"
      - "postgres-volume:/var/lib/postgresql/data"
    networks:
      net: {}

  redis:
    #image: redis_custom:alpha
    build:
      context: Dockerfile-Redis
      dockerfile: Dockerfile
    ports:
      - 6379:6379
    volumes: 
      - ./volumes/volume-redis:/data
    networks:
      net: {}

  
  apache-flask:
    #image: apache2_custom:alpha
    build:
      context: Dockerfile-Apache
      dockerfile: Dockerfile
    ports:
      - 8888:80
    networks:
      net: {}


  admirer:
    image: adminer
    ports:
      - 8020:8080
    networks:
      net: {}

networks:
  net: {}

volumes:
  postgres-volume: